=== neibibitoi/31284ass/WebContent/db/hotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<!-- Insert your type declarations here -->

	<!-- Insert your element declarations here -->

	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="hotels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="hotel" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="city" type="xs:string" />
										<xs:element name="country" type="xs:string" />
										<xs:element name="id" type="xs:positiveInteger" />
										<xs:element name="name" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== neibibitoi/31284ass/WebContent/db/hotel.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="hotel.xsd">
    <hotels>
        <hotel>
            <city>sydney</city>
            <country>AU</country>
            <id>1</id>
            <name>hotel 1</name>
        </hotel>
        <hotel>
            <city>sydney</city>
            <country>CA</country>
            <id>2</id>
            <name>hotel 2</name>
        </hotel>
    </hotels>
</root>
